version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: primecapital-app
    restart: always
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ../src:/app
      - ../data:/data
      - ../output:/output
    environment:
      FLASK_ENV: development
